### ISSUE TITLE
Undefined Reference to GLIB

### ISSUE THREAD

**Issue by nilleko** [Fields2Cover/Fields2Cover#159]
Building on ubuntu20.4:

cmake version 3.29.5

or-tools:
Downloaded binaries and ran "make test" succesfully.

Followed subsequent instructions for installing F2C.

Getting stuck at the 
make -j$(nproc);
step.. Throws SEVERAL errors similar to these:
/usr/bin/ld: /home/niclas/Fields2Cover/build/_deps/ortools-src/lib/libortools.so.9: undefined reference to `std::condition_variable::wait(std::unique_lock<std::mutex>&)@GLIBCXX_3.4.30'
/usr/bin/ld: /home/niclas/Fields2Cover/build/_deps/ortools-src/lib/libortools.so.9: undefined reference to `pthread_detach@GLIBC_2.34'
/usr/bin/ld: /home/niclas/Fields2Cover/build/_deps/ortools-src/lib/libortools.so.9: undefined reference to `pthread_key_delete@GLIBC_2.34'
/usr/bin/ld: /home/niclas/Fields2Cover/build/_deps/ortools-src/lib/libortools.so.9: undefined reference to `std::to_chars(char*, char*, double)@GLIBCXX_3.4.29'
/usr/bin/ld: /home/niclas/Fields2Cover/build/_deps/ortools-src/lib/libortools.so.9: undefined reference to `dlsym@GLIBC_2.34'

I have succesfully installed it on an ubuntu24 system. Verified by being able to import the library in python3 "import fields2cover".

Thanks in advance

**Comment by aosmw** [comment]
The GLIBC error is probably caused by using a binary release of ortools (-DUSE_ORTOOLS_RELEASE=ON) on a system that is not compatiable with it.  Ubuntu 20.04 has glibc 2.31

I was going to say try 
```
mkdir -p build;
cd build;
cmake -DCMAKE_BUILD_TYPE=Release -DUSE_ORTOOLS_RELEASE=OFF -DUSE_ORTOOLS_FETCH_SRC=ON -DCMAKE_BUILD_TYPE=Release -DBUILD_PYTHON=ON -DBUILD_TESTS=ON ..;
make -j$(nproc)
```

Which builds ortools from source but I just did it and got 
'''
CMake Error at CMakeLists.txt:361 (add_custom_target):
  add_custom_target cannot create target "check" because another target with
  the same name already exists.  The existing target is an interface library
  created in source directory
  "/home/wakem/dev/contrib_github/n2/src/Fields2Cover/build/_deps/abseil-cpp-src/absl/log".
  See documentation for policy CMP0002 for more details.
'''

Which is a conflict in target names.

**Comment by Gonzalo-Mier** [comment]
Feel free to reopen the issue if it happens again
