### ISSUE TITLE
Not completely covering field

### ISSUE THREAD

**Issue by Rick-v-E** [Fields2Cover/Fields2Cover#70]
Hi,

I am using Fields2Cover for covering a complete field with a drone. As example, I have a field of 48x48 and a drone with a field-of-view of 11x11. Here is the code to generate the `swaths`:

```python
import fields2cover as f2c
import numpy as np

robot = f2c.Robot(11.0, 11.0)
robot.setMinRadius(0)
robot.start_point = f2c.optional_Point(f2c.Point(3.0, 4.0))
robot.linear_curv_change = 0

field_border = f2c.LinearRing()
field_border.addPoint(0, 0)
field_border.addPoint(0, 47)
field_border.addPoint(47, 47)
field_border.addPoint(47, 0)
field_border.addPoint(field_border.StartPoint())

field_cell = f2c.Cell()
field_cell.addRing(field_border)

field = f2c.Field()
field.field.addGeometry(field_cell)

# Generate no headland
const_hl = f2c.HG_Const_gen()
no_hl = const_hl.generateHeadlands(field.field, 0)
bf = f2c.SG_BruteForce()

swaths = bf.generateSwaths(np.pi, robot.op_width, no_hl.getGeometry(0))

sorter = f2c.RP_Boustrophedon()
swaths = sorter.genSortedSwaths(swaths)


print(swaths)

f2c.Visualizer.figure(100)
f2c.Visualizer.plot(swaths)
f2c.Visualizer.show()
```

The produced `swaths`:
```commandline
SWATHS(SWATH([(41.5, 0, 0), (41.5, 47, 0)], width = 11), SWATH([(30.5, 47, 0), (30.5, 0, 0)], width = 11), SWATH([(19.5, 0, 0), (19.5, 47, 0)], width = 11), SWATH([(8.5, 47, 0), (8.5, 0, 0)], width = 11))
```

The produced figure:

![Figure_100](https://github.com/Fields2Cover/Fields2Cover/assets/78429257/5fdaf814-5d41-4c48-899d-96ea69973680)

On the right side of the field, the drone is covering till the end of the field (41.5 + 11/2 = 47), which is how I expected it. However, on the left side of the field, a strip with width 3 (8.5 - 11/2 = 3) is not covered. I would expect that there would be another `swath` that covers this strip of 3. Did I do something wrong in the code above?

**Comment by Gonzalo-Mier** [comment]
Hi @Rick-v-E, 
No, you didn't do anything wrong. About this, I have to say that _**this is not a bug, but a feature**_. When designing the library, we were concerned that covering a field without headlands could lead a robot to get out of the field. Because of this you get on one side an exact border coverage, and in the other some uncovered space. The other option would have been to do one more swath, and cover some area outside the field.

To solve it, change [this line](https://github.com/Fields2Cover/Fields2Cover/blob/b7366c32367052a1c6c10e9378197a92fa42fa28/include/fields2cover/swath_generator/swath_generator_base_impl.hpp#LL46C2-L46C2) by `for (int i = 0; i <= n_swaths; ++i) {`.

We don't have time right now to improve this section now, but feel free to change it in your code or submit a PR making this behavior optional.
