### ISSUE TITLE
Map API: AerialmapDisplay && Path sequences

### ISSUE THREAD

**Issue by Stoner-F** [Fields2Cover/Fields2Cover#99]
Dear Professor, 

Hi, First of all, thanks for your work. I have been very benefited and am currently reading your code. I have two questions to ask you.
1. "AerialmapDisplay (https://github.com/nobleo/rviz_satellite) returns the map from [OpenStreetMap](https://www.openstreetmap.org/). It is only required for visualization purposes."  But I have a guess that I don't know if it's feasible: based on the project, connect to the map API, specify the coordinates of the area boundary points (longitude, latitude), and then generate a feasible operation path.
2. I noticed while reading your paper that you conducted a field experiment. I am particularly interested in experiments and would like to ask you if the current version of Field2Cover can generate paths that can be tracked by vehicles?  If so, how can I obtain path sequences? I noticed that you used Protobuf. If you could provide me with code(field experiment) or some reference demos for me to learn, I would be very grateful.

Looking forward to your reply, thank you again for your work！

**Comment by Gonzalo-Mier** [comment]
Hi @Stoner-F,

Thanks for calling me Professor, but I'm not yet a professor haha. 

> But I have a guess that I don't know if it's feasible: based on the project, connect to the map API, specify the coordinates of the area boundary points (longitude, latitude), and then generate a feasible operation path.

Yes, it's possible. It is exactly what [fields2cover_ros](https://github.com/Fields2Cover/fields2cover_ros) does.

> I am particularly interested in experiments and would like to ask you if the current version of Field2Cover can generate paths that can be tracked by vehicles? If so, how can I obtain path sequences?

Tutorials are located here: https://fields2cover.github.io/source/tutorials.html

> I noticed that you used Protobuf.

It is used to communicate with our particular robot, but each robot has its own interface. That bridge cannot be provided by us, because it depends on each commercial product.
